Merge add-controllers
Nagash40/java-shareit pull request #1
Opened 2022-10-23 13:09 UTC by Nagash40

Андрей, добрый день.
В соответствии с требованиями ТЗ и тестов реализован функционал для добавления, получения и обновления вещей, а также для добавления, получения, обновления и удаления пользователей.
Директории, в которых нужно реализовывать функционал в будущих спринтах (request, booking), оставлены без изменений.

2022-10-23 17:48 UTC, andrew-larkin requested changes
Привет! Хочу сказать, что код очень качественный, промышленного уровня. Логика, конструкции реализованы очень удачно. Остается немного отрефакторить и будет готово. Если будут вопросы по правкам - можно писать мне в Слак.

2022-10-23 17:48 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +@AllArgsConstructor
возможно, здесь лучше подойдет @RequiredArgsConstructor - он добавит в конструктор только final переменные, которые мы хотим внедрить в виде зависимости и не зааффектит, если мы добавим не final переменные в дальнейшем

2022-10-23 17:48 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
если есть время, предлагаю взглянуть на маленькую библиотеку mapStruct, она автоматизирует создание мапперов, код написанный ниже превратится в одну строчку. Но это только на твое усмотрение

2022-10-23 17:48 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +@AllArgsConstructor
@RequiredArgsConstructor

2022-10-23 17:48 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/item/repository/InMemoryItemRepositoryTest.java
> +    ItemRepository itemRepository;
в тестах переменные лучше указывать с модификатором доступа private

2022-10-23 17:48 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +public class UserControllerTest {
также если будет время советую посмотреть на mockMvc. его используют почаще, чем testRestTemplate, он в дальнейшем очень пригодится. Но это также - только по твоему желанию. Так тесты написаны хорошо

2022-10-23 17:48 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +        UserDto userDto = makeDefaultUserDto();
чтобы не дублировать создание dto в каждом тесте, предлагаю вынести создание в отдельный приватный метод, в котором будет создаваться "корректный" dto. Затем ты будешь вызывать этот метод в тестах, и там где нужно изменить какое-то поле dto, просто воспользуешься сеттером

2022-10-24 20:28 UTC, Nagash40 commented
Привет, отправляю на ревью новый коммит.
Правки добавлены по всем комментариям.

2022-10-24 21:16 UTC, merged