ТЗ-14
Nagash40/java-shareit pull request #2
Opened 2022-11-15 20:58 UTC by Nagash40

Андрей, добрый день.
Отправляю на проверку ТЗ 14 спринта. По требованиям все реализовано, внутренние тесты допишу в рамках следующего задания - на проект уже ушло очень много времени и следующее ТЗ, насколько я понимаю, во многом посвящено покрытию всего реализованного функционала тестами.

2022-11-16 16:39 UTC, andrew-larkin requested changes
Привет! Отлично, очень качественная работа. Нам остается немного привести ее в порядок, я все оставил комментарии по коду только в папке booking, но они актуальны для всех остальных папок. Небольшой рефакторинг и мы будем готовы двигаться дальше.

2022-11-16 16:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final BookingMapper mapper;
маппер стоит перенести на уровень сервисов, контроллер должен вызывать только методы сервисов без дополнительной логики

2022-11-16 16:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        LocalDateTime start = bookingDto.getStart();
вся эта логика должна быть в сервисе

2022-11-16 16:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private BookingStatus parseStatus(String state) {
приватные методы также только в сервисах

2022-11-16 16:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +public interface BookingMapper {
отлично, большой плюс за использование мапперов

2022-11-16 16:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Collection<Booking> getAllByBookerIdOrItemOwnerIdAndApprovedIsOrderByStartTimeDesc(
большой плюс за JPQL-запросы. По идее, если мы используем такой запрос, то название самого метода может быть любым, т.е. его можно сделать покороче

2022-11-16 16:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +    public Booking addBooking(Booking booking) {
возвращать в контроллер лучше всего именно dto, т.к. возврат объекта модели целиком является плохой практикой

2022-11-16 16:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingStatus.java
> +public enum BookingStatus {
этот enum лучше перенести в папку с моделями

2022-11-17 17:39 UTC, Nagash40 commented
Из контроллеров вынесено все, кроме обычных вызовов сервисов и отправки ответов, все затронутые рефакторингом тесты изменены для работы с новой логикой.
Из небольших изменений переименована часть длинных методов, работающих с JPQL,, и перемещен в директорию с DTO enum со статусами.

2022-11-19 10:14 UTC, merged