ТЗ-15
Nagash40/java-shareit pull request #3
Opened 2022-11-22 15:16 UTC by Nagash40

2022-11-22 21:53 UTC, Nagash40 commented
Андрей, добрый день.
Добавлен функционал с запросами и дописаны тесты. 
Из значимого в тестах - для репозиториев использована аннотация @DataJpaTest, чтобы убрать ненужную загрузку контекста. В остальном я использовал те же инструменты для написания интеграционных тестов, которые применял в прошлых ТЗ.

К объектам моделей и интерфейсам с пустой (и автогенерируемой) реализацией добавлена аннотация @Generated, чтобы преодолеть не самые адекватные требования о покрытии кода тестами (целевые уровни покрытия не менял).

2022-11-23 15:50 UTC, andrew-larkin requested changes
Привет! Не хватает пагинации. В booking я оставил комментарии - они актуальны для всех контроллеров и сервисов. И в одном из тестов надо поправить assert.

2022-11-23 15:50 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/request/repository/ItemRequestRepositoryTest.java
> +        assertEquals(List.of(request2, request1),
падает вот этот assert

2022-11-23 15:50 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        if (size == null) {
всю логику нужно перенести в сервис, тут будет только вызов метода сервиса без доп.логики

2022-11-23 15:50 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        if (size == null) {
и здесь тоже

2022-11-23 15:50 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
>      public ResponseEntity<Collection<BookingDto>> getBookingsByOwnerAndStatus(
чтобы не отправлять в ответе голую коллекцию, можно создать еще один dto (BookingListDto), куда положить эту коллекцию. json при этом не изменится, но визуально будет выглядеть менее нагруженно

2022-11-23 15:50 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +public interface ItemRequestRepository extends JpaRepository<ItemRequest, Long> {
не увидел пагинации - стоит унаследоваться от PagingAndSortingRepository, передавать в запросах объект Pageable

2022-11-23 19:29 UTC, Nagash40 commented
Высылаю новую версию - вынес из контроллеров в сервисы лишнюю логику и поменял логику работы в пагинацией для использования репозиториев типа PagingAndSortingRepository.

Я не стал менять передачу коллекции на передачу коллекции в объекте, поскольку тесты постмана в текущем виде ожидают, что в теле ответа будет лежать голая коллекция. Проверка тела ответа начинается со строк вроде этой:
var jsonData = pm.response.json();
    pm.expect(jsonData.length, 'bookings count in total').to.eql(1);

Если передавать объект вместо коллекции, проект перестанет проходить постмановские тесты в GitHub Actions. Теоретически я могу создать новый класс и изменить правила его сериализации, чтобы на фронт уходила голая коллекция, но это лишает смысла упаковку коллекции в объект.

2022-11-24 16:13 UTC, merged